const groupsNames = [
"Base Game",
"Events",
"Outdoor Retreat",
"Spa Day",
"Get Together",
"City Living",
"Vampires",
"Parenthood",
"Cats and Dogs",
"Jungle Adventure",
"Get Famous",
"StrangerVille",
"Island Living",
"Realm of Magic",
"Discover University",
"Eco Lifestyle",
"Nifty Knitting",
"Batuu",
"Snowy Escape",
"Bust the Dust",
"Cottage Living",
"Werewolves",
"Horse Ranch",
"Home Chef Hustle",
"Crystal Creations",
"For Rent",
"Lovestruck",
"Life & Death",
"Businesses & Hobbies",
"Enchanted by Nature",
];

const groups = [
	['Angling Ace', 'Bestselling Author', 'Big Happy Family', 'Bodybuilder', 'Chief of Mischief', 'Computer Whiz', 'Fabulously Wealthy', 'Freelance Botanist', 'Friend of the World', 'Joke Star', 'Mansion Baron', 'Master Chef', 'Master Mixologist', 'Musical Genius', 'Neighborhood Confidante', 'Nerd Brain', 'Painter Extraordinaire', 'Party Animal', 'Public Enemy', 'Renaissance Sim', 'Serial Romantic', 'Soulmate', 'Successful Lineage', 'The Curator', 'Villainous Valentine'],
	['Sticky Fingers'],
	['Outdoor Enthusiast'],
	['Inner Peace','Self-Care Specialist','Zen Guru'],
	['Leader of the Pack'],
	['City Native'],
	['Good Vampire', 'Master Vampire', 'Vampire Family'],
	['Super Parent'],
	['Friend of the Animals'],
	['Archaeology Scholar','Jungle Explorer'],
	['Master Actor','World-Famous Celebrity'],
	['StrangerVille Mystery'],
	['Beach Life'],
	['Purveyor of Potions','Spellcraft & Sorcery'],
	['Academic'],
	['Eco Innovator','Master Maker'],
	['Lord/Lady of the Knits'],
	['Galactic Privateer','Hope VS Order','Paragon of Hope','Enforcer of Order'],
	['Extreme Sports Enthusiast','Mt. Komorebi Sightseer'],
	['Fabulously Filthy','Perfectly Pristine'],
	['Country Caretaker'],
	['Werewolf Initiate','Emissary of the Collective','Wildfang Renegade','Lone Wolf','Cure Seeker'],
	['Championship Rider','Expert Nectar Maker'],
	['Appliance Whiz','Market Magnate'],
	['Crystal Crafter'],
	['Discerning Dweller','Five-Star Property Owner','Fount of Tomarani Knowledge','Seeker of Secrets'],
	['Romantic Explorer','Paragon Partner'],
	['Ghost Historian'],
	['Master Mentor','Esteemed Entrepreneur'],
	['Natural Nomad','Fairy Stories','Elixir Enthusiast'],
];

const secretMessages = {
 'Angling Ace': { message: 'Nature'},
 'Bestselling Author': { message: 'Creativity'},
 'Big Happy Family': { message: 'Family'},
 'Bodybuilder': { message: 'Athletic'},
 'Chief of Mischief': { message: 'Deviance'},
 'Computer Whiz': { message: 'Knowledge'},
 'Fabulously Wealthy': { message: 'Fortune'},
 'Freelance Botanist': { message: 'Nature'},
 'Friend of the World': { message: 'Popularity'},
 'Joke Star': { message: 'Popularity'},
 'Mansion Baron': { message: 'Fortune'},
 'Master Chef': { message: 'Food'},
 'Master Mixologist': { message: 'Food'},
 'Musical Genius': { message: 'Creativity'},
 'Neighborhood Confidante': { message: 'Popularity'},
 'Nerd Brain': { message: 'Knowledge'},
 'Painter Extraordinaire': { message: 'Creativity'},
 'Party Animal': { message: 'Popularity'},
 'Public Enemy': { message: 'Deviance'},
 'Renaissance Sim': { message: 'Knowledge'},
 'Serial Romantic': { message: 'Love'},
 'Soulmate': { message: 'Love'},
 'Successful Lineage': { message: 'Family'},
 'The Curator': { message: 'Nature'},
 'Villainous Valentine': { message: 'Deviance'},
 'Sticky Fingers': { message: 'Deviance'},
 'Outdoor Enthusiast': { message: 'Nature'},
 'Inner Peace': { message: 'Wellness'},
 'Self-Care Specialist': { message: 'Wellness'},
 'Zen Guru': { message: 'Wellness'},
 'Leader of the Pack': { message: 'Popularity'},
 'City Native': { message: 'Location'},
 'Good Vampire': { message: 'Popularity'},
 'Master Vampire': { message: 'Knowledge'},
 'Vampire Family': { message: 'Family'},
 'Super Parent': { message: 'Family'},
 'Friend of the Animals': { message: 'Animal'},
 'Archaeology Scholar': { message: 'Knowledge'},
 'Jungle Explorer': { message: 'Nature'},
 'Master Actor': { message: 'Creativity'},
 'World-Famous Celebrity': { message: 'Popularity'},
 'StrangerVille Mystery': { message: 'Location'},
 'Beach Life': { message: 'Location'},
 'Purveyor of Potions': { message: 'Nature'},
 'Spellcraft & Sorcery': { message: 'Knowledge'},
 'Academic': { message: 'Knowledge'},
 'Eco Innovator': { message: 'Nature'},
 'Master Maker': { message: 'Creativity'},
 'Lord/Lady of the Knits': { message: 'Creativity'},
 'Galactic Privateer': { message: 'Star Wars'},
 'Hope VS Order': { message: 'Star Wars'},
 'Paragon of Hope': { message: 'Star Wars'},
 'Enforcer of Order': { message: 'Star Wars'},
 'Extreme Sports Enthusiast': { message: 'Athletic'},
 'Mt. Komorebi Sightseer': { message: 'Location'},
 'Fabulously Filthy': { message: 'Location'},
 'Perfectly Pristine': { message: 'Location'},
 'Country Caretaker': { message: 'Nature'},
 'Werewolf Initiate': { message: 'Werewolf'},
 'Emissary of the Collective': { message: 'Werewolf'},
 'Wildfang Renegade': { message: 'Werewolf'},
 'Lone Wolf': { message: 'Werewolf'},
 'Cure Seeker': { message: 'Werewolf'},
 'Championship Rider': { message: 'Athletic'},
 'Expert Nectar Maker': { message: 'Food'},
 'Appliance Whiz': { message: 'Food'},
 'Market Magnate': { message: 'Fortune'},
 'Crystal Crafter': { message: 'Nature'},
 'Discerning Dweller': { message: 'Popularity'},
 'Five-Star Property Owner': { message: 'Fortune'},
 'Fount of Tomarani Knowledge': { message: 'Location'},
 'Seeker of Secrets': { message: 'Deviance'},
 'Romantic Explorer': { message: 'Love'},
 'Paragon Partner': { message: 'Love'},
 'Ghost Historian': { message: 'Knowledge'},
 'Master Mentor': { message: 'Knowledge'},
 'Esteemed Entrepreneur': { message: 'Popularity'},
 'Natural Nomad': { message: 'Nature'},
 'Fairy Stories': { message: 'Fairy'},
 'Elixir Enthusiast': { message: 'Knowledge'},
};

const numOfGroups = groupsNames.length;